{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"setup","msg":"Starting CloudNativePG Instance Manager","logging_pod":"cluster-example-1","version":"1.19.1","build":{"Version":"1.19.1","Commit":"cb24d237","Date":"2023-03-20"}}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"setup","msg":"starting controller-runtime manager","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Starting EventSource","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","source":"kind source: *v1.Cluster"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Starting Controller","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Starting webserver","logging_pod":"cluster-example-1","address":":9187"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Starting webserver","logging_pod":"cluster-example-1","address":":8000"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Starting webserver","logging_pod":"cluster-example-1","address":"localhost:8010"}
{"level":"debug","ts":"2023-03-23T15:21:57Z","msg":"starting the postgres loop","caller":"pkg/management/log/log.go:181","logging_pod":"cluster-example-1"}
{"level":"debug","ts":"2023-03-23T15:21:57Z","msg":"starting signal loop","caller":"pkg/management/log/log.go:181","logging_pod":"cluster-example-1"}
{"level":"debug","ts":"2023-03-23T15:21:57Z","msg":"Checking PGDATA coherence","caller":"internal/cmd/manager/instance/run/lifecycle/run.go:255","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Starting workers","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","worker count":1}
{"level":"debug","ts":"2023-03-23T15:21:57Z","msg":"Reconciling Cluster","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c005e286-d53f-4ac1-9971-49554132cf3b","uuid":"73172b16-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:109","logging_pod":"cluster-example-1","cluster":{"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","namespace":"default","name":"cluster-example"}}
{"level":"debug","ts":"2023-03-23T15:21:57Z","msg":"Reconciling custom monitoring queries","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c005e286-d53f-4ac1-9971-49554132cf3b","uuid":"73172b16-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:727","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Refreshed configuration file","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c005e286-d53f-4ac1-9971-49554132cf3b","uuid":"73172b16-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","filename":"/controller/certificates/server.crt","secret":"cluster-example-server"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Refreshed configuration file","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c005e286-d53f-4ac1-9971-49554132cf3b","uuid":"73172b16-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","filename":"/controller/certificates/server.key","secret":"cluster-example-server"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Refreshed configuration file","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c005e286-d53f-4ac1-9971-49554132cf3b","uuid":"73172b16-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","filename":"/controller/certificates/streaming_replica.crt","secret":"cluster-example-replication"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Refreshed configuration file","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c005e286-d53f-4ac1-9971-49554132cf3b","uuid":"73172b16-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","filename":"/controller/certificates/streaming_replica.key","secret":"cluster-example-replication"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Refreshed configuration file","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c005e286-d53f-4ac1-9971-49554132cf3b","uuid":"73172b16-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","filename":"/controller/certificates/client-ca.crt","secret":"cluster-example-ca"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Refreshed configuration file","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c005e286-d53f-4ac1-9971-49554132cf3b","uuid":"73172b16-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","filename":"/controller/certificates/server-ca.crt","secret":"cluster-example-ca"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Cluster status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c005e286-d53f-4ac1-9971-49554132cf3b","uuid":"73172b16-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"This is an old primary instance, waiting for the switchover to finish","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c005e286-d53f-4ac1-9971-49554132cf3b","uuid":"73172b16-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Switchover completed","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c005e286-d53f-4ac1-9971-49554132cf3b","uuid":"73172b16-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","targetPrimary":"cluster-example-2","currentPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Waiting for the new primary to be available","logging_pod":"cluster-example-1","primaryConnInfo":"host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres connect_timeout=5"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Extracting pg_controldata information","logging_pod":"cluster-example-1","reason":"before pg_rewind"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_controldata","msg":"pg_control version number:            1300\nCatalog version number:               202209061\nDatabase system identifier:           7213723966086483989\nDatabase cluster state:               shut down\npg_control last modified:             Thu 23 Mar 2023 03:15:11 PM UTC\nLatest checkpoint location:           0/8000028\nLatest checkpoint's REDO location:    0/8000028\nLatest checkpoint's REDO WAL file:    000000030000000000000008\nLatest checkpoint's TimeLineID:       3\nLatest checkpoint's PrevTimeLineID:   3\nLatest checkpoint's full_page_writes: on\nLatest checkpoint's NextXID:          0:741\nLatest checkpoint's NextOID:          24578\nLatest checkpoint's NextMultiXactId:  1\nLatest checkpoint's NextMultiOffset:  0\nLatest checkpoint's oldestXID:        716\nLatest checkpoint's oldestXID's DB:   1\nLatest checkpoint's oldestActiveXID:  0\nLatest checkpoint's oldestMultiXid:   1\nLatest checkpoint's oldestMulti's DB: 1\nLatest checkpoint's oldestCommitTsXid:0\nLatest checkpoint's newestCommitTsXid:0\nTime of latest checkpoint:            Thu 23 Mar 2023 03:15:10 PM UTC\nFake LSN counter for unlogged rels:   0/3E8\nMinimum recovery ending location:     0/0\nMin recovery ending loc's timeline:   0\nBackup start location:                0/0\nBackup end location:                  0/0\nEnd-of-backup record required:        no\nwal_level setting:                    logical\nwal_log_hints setting:                on\nmax_connections setting:              100\nmax_worker_processes setting:         32\nmax_wal_senders setting:              10\nmax_prepared_xacts setting:           0\nmax_locks_per_xact setting:           64\ntrack_commit_timestamp setting:       off\nMaximum data alignment:               8\nDatabase block size:                  8192\nBlocks per segment of large relation: 131072\nWAL block size:                       8192\nBytes per WAL segment:                16777216\nMaximum length of identifiers:        64\nMaximum columns in an index:          32\nMaximum size of a TOAST chunk:        1996\nSize of a large-object chunk:         2048\nDate/time type storage:               64-bit integers\nFloat8 argument passing:              by value\nData page checksum version:           0\nMock authentication nonce:            b7f2f04197c763627732f064e0e1fca36c334973d9441ff8e49c207f6cd5a38f\n","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Starting up pg_rewind","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"]}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_rewind","msg":"pg_rewind: error: restore_command is not set in the target cluster","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:57Z","msg":"Failed to execute pg_rewind","logging_pod":"cluster-example-1","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"],"error":"exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*Instance).Rewind\n\tpkg/management/postgres/instance.go:783\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).verifyPgDataCoherenceForPrimary\n\tinternal/management/controller/instance_startup.go:235\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).initialize\n\tinternal/management/controller/instance_controller.go:327\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).Reconcile\n\tinternal/management/controller/instance_controller.go:141\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"pg_rewind failed, starting the server to complete the crash recovery","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c005e286-d53f-4ac1-9971-49554132cf3b","uuid":"73172b16-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","err":"error executing pg_rewind: exit status 1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Waiting for server to complete crash recovery","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Starting up instance","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["start","-w","-D","/var/lib/postgresql/data/pgdata","-o","-c port=5432 -c unix_socket_directories=/controller/run","-t 40000000"]}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"waiting for server to start....2023-03-23 15:21:57.280 GMT [27] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.280 GMT [27] LOG:  listening on IPv6 address \"::1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.280 GMT [27] LOG:  listening on IPv4 address \"127.0.0.1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.286 GMT [27] LOG:  listening on Unix socket \"/controller/run/.s.PGSQL.5432\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.289 GMT [27] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.289 GMT [27] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.289 GMT [27] CONTEXT:  line 6 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.289 GMT [27] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.289 GMT [27] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.289 GMT [27] CONTEXT:  line 7 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.289 GMT [27] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.289 GMT [27] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.289 GMT [27] CONTEXT:  line 8 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.292 GMT [30] LOG:  database system was shut down at 2023-03-23 15:15:11 GMT","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.293 GMT [30] LOG:  invalid primary checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.293 GMT [30] PANIC:  could not locate a valid checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.384 GMT [27] LOG:  startup process (PID 30) was terminated by signal 6: Aborted","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.384 GMT [27] LOG:  aborting startup due to startup process failure","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.385 GMT [27] LOG:  database system is shut down","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":" stopped waiting","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"pg_ctl: could not start server","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"Examine the log output.","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Exited log pipe","fileName":"/controller/log/postgres.csv","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:57Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c005e286-d53f-4ac1-9971-49554132cf3b","error":"while activating instance: error starting PostgreSQL instance: exit status 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"debug","ts":"2023-03-23T15:21:57Z","msg":"Reconciling Cluster","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"1c51ca22-954d-40e8-ad5e-cba1e3bd6b23","uuid":"7342d0ac-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:109","logging_pod":"cluster-example-1","cluster":{"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","namespace":"default","name":"cluster-example"}}
{"level":"debug","ts":"2023-03-23T15:21:57Z","msg":"Reconciling custom monitoring queries","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"1c51ca22-954d-40e8-ad5e-cba1e3bd6b23","uuid":"7342d0ac-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:727","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Cluster status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"1c51ca22-954d-40e8-ad5e-cba1e3bd6b23","uuid":"7342d0ac-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"This is an old primary instance, waiting for the switchover to finish","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"1c51ca22-954d-40e8-ad5e-cba1e3bd6b23","uuid":"7342d0ac-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Switchover completed","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"1c51ca22-954d-40e8-ad5e-cba1e3bd6b23","uuid":"7342d0ac-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","targetPrimary":"cluster-example-2","currentPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Waiting for the new primary to be available","logging_pod":"cluster-example-1","primaryConnInfo":"host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres connect_timeout=5"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Extracting pg_controldata information","logging_pod":"cluster-example-1","reason":"before pg_rewind"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_controldata","msg":"pg_control version number:            1300\nCatalog version number:               202209061\nDatabase system identifier:           7213723966086483989\nDatabase cluster state:               shut down\npg_control last modified:             Thu 23 Mar 2023 03:15:11 PM UTC\nLatest checkpoint location:           0/8000028\nLatest checkpoint's REDO location:    0/8000028\nLatest checkpoint's REDO WAL file:    000000030000000000000008\nLatest checkpoint's TimeLineID:       3\nLatest checkpoint's PrevTimeLineID:   3\nLatest checkpoint's full_page_writes: on\nLatest checkpoint's NextXID:          0:741\nLatest checkpoint's NextOID:          24578\nLatest checkpoint's NextMultiXactId:  1\nLatest checkpoint's NextMultiOffset:  0\nLatest checkpoint's oldestXID:        716\nLatest checkpoint's oldestXID's DB:   1\nLatest checkpoint's oldestActiveXID:  0\nLatest checkpoint's oldestMultiXid:   1\nLatest checkpoint's oldestMulti's DB: 1\nLatest checkpoint's oldestCommitTsXid:0\nLatest checkpoint's newestCommitTsXid:0\nTime of latest checkpoint:            Thu 23 Mar 2023 03:15:10 PM UTC\nFake LSN counter for unlogged rels:   0/3E8\nMinimum recovery ending location:     0/0\nMin recovery ending loc's timeline:   0\nBackup start location:                0/0\nBackup end location:                  0/0\nEnd-of-backup record required:        no\nwal_level setting:                    logical\nwal_log_hints setting:                on\nmax_connections setting:              100\nmax_worker_processes setting:         32\nmax_wal_senders setting:              10\nmax_prepared_xacts setting:           0\nmax_locks_per_xact setting:           64\ntrack_commit_timestamp setting:       off\nMaximum data alignment:               8\nDatabase block size:                  8192\nBlocks per segment of large relation: 131072\nWAL block size:                       8192\nBytes per WAL segment:                16777216\nMaximum length of identifiers:        64\nMaximum columns in an index:          32\nMaximum size of a TOAST chunk:        1996\nSize of a large-object chunk:         2048\nDate/time type storage:               64-bit integers\nFloat8 argument passing:              by value\nData page checksum version:           0\nMock authentication nonce:            b7f2f04197c763627732f064e0e1fca36c334973d9441ff8e49c207f6cd5a38f\n","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Starting up pg_rewind","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"]}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_rewind","msg":"pg_rewind: error: restore_command is not set in the target cluster","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:57Z","msg":"Failed to execute pg_rewind","logging_pod":"cluster-example-1","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"],"error":"exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*Instance).Rewind\n\tpkg/management/postgres/instance.go:783\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).verifyPgDataCoherenceForPrimary\n\tinternal/management/controller/instance_startup.go:235\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).initialize\n\tinternal/management/controller/instance_controller.go:327\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).Reconcile\n\tinternal/management/controller/instance_controller.go:141\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"pg_rewind failed, starting the server to complete the crash recovery","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"1c51ca22-954d-40e8-ad5e-cba1e3bd6b23","uuid":"7342d0ac-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","err":"error executing pg_rewind: exit status 1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Waiting for server to complete crash recovery","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Starting up instance","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["start","-w","-D","/var/lib/postgresql/data/pgdata","-o","-c port=5432 -c unix_socket_directories=/controller/run","-t 40000000"]}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"waiting for server to start....2023-03-23 15:21:57.541 GMT [41] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.541 GMT [41] LOG:  listening on IPv6 address \"::1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.541 GMT [41] LOG:  listening on IPv4 address \"127.0.0.1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.546 GMT [41] LOG:  listening on Unix socket \"/controller/run/.s.PGSQL.5432\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.549 GMT [41] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.549 GMT [41] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.549 GMT [41] CONTEXT:  line 6 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.549 GMT [41] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.549 GMT [41] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.549 GMT [41] CONTEXT:  line 7 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.549 GMT [41] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.549 GMT [41] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.549 GMT [41] CONTEXT:  line 8 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.555 GMT [44] LOG:  database system was shut down at 2023-03-23 15:15:11 GMT","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.555 GMT [44] LOG:  invalid primary checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.555 GMT [44] PANIC:  could not locate a valid checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.650 GMT [41] LOG:  startup process (PID 44) was terminated by signal 6: Aborted","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.650 GMT [41] LOG:  aborting startup due to startup process failure","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.651 GMT [41] LOG:  database system is shut down","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":" stopped waiting","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"pg_ctl: could not start server","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"Examine the log output.","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Exited log pipe","fileName":"/controller/log/postgres.csv","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:57Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"1c51ca22-954d-40e8-ad5e-cba1e3bd6b23","error":"while activating instance: error starting PostgreSQL instance: exit status 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"debug","ts":"2023-03-23T15:21:57Z","msg":"Reconciling Cluster","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"a8daf6ad-0a1e-46eb-891a-179e31abb133","uuid":"736bbc18-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:109","logging_pod":"cluster-example-1","cluster":{"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","namespace":"default","name":"cluster-example"}}
{"level":"debug","ts":"2023-03-23T15:21:57Z","msg":"Reconciling custom monitoring queries","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"a8daf6ad-0a1e-46eb-891a-179e31abb133","uuid":"736bbc18-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:727","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Cluster status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"a8daf6ad-0a1e-46eb-891a-179e31abb133","uuid":"736bbc18-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"This is an old primary instance, waiting for the switchover to finish","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"a8daf6ad-0a1e-46eb-891a-179e31abb133","uuid":"736bbc18-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Switchover completed","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"a8daf6ad-0a1e-46eb-891a-179e31abb133","uuid":"736bbc18-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","targetPrimary":"cluster-example-2","currentPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Waiting for the new primary to be available","logging_pod":"cluster-example-1","primaryConnInfo":"host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres connect_timeout=5"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Extracting pg_controldata information","logging_pod":"cluster-example-1","reason":"before pg_rewind"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_controldata","msg":"pg_control version number:            1300\nCatalog version number:               202209061\nDatabase system identifier:           7213723966086483989\nDatabase cluster state:               shut down\npg_control last modified:             Thu 23 Mar 2023 03:15:11 PM UTC\nLatest checkpoint location:           0/8000028\nLatest checkpoint's REDO location:    0/8000028\nLatest checkpoint's REDO WAL file:    000000030000000000000008\nLatest checkpoint's TimeLineID:       3\nLatest checkpoint's PrevTimeLineID:   3\nLatest checkpoint's full_page_writes: on\nLatest checkpoint's NextXID:          0:741\nLatest checkpoint's NextOID:          24578\nLatest checkpoint's NextMultiXactId:  1\nLatest checkpoint's NextMultiOffset:  0\nLatest checkpoint's oldestXID:        716\nLatest checkpoint's oldestXID's DB:   1\nLatest checkpoint's oldestActiveXID:  0\nLatest checkpoint's oldestMultiXid:   1\nLatest checkpoint's oldestMulti's DB: 1\nLatest checkpoint's oldestCommitTsXid:0\nLatest checkpoint's newestCommitTsXid:0\nTime of latest checkpoint:            Thu 23 Mar 2023 03:15:10 PM UTC\nFake LSN counter for unlogged rels:   0/3E8\nMinimum recovery ending location:     0/0\nMin recovery ending loc's timeline:   0\nBackup start location:                0/0\nBackup end location:                  0/0\nEnd-of-backup record required:        no\nwal_level setting:                    logical\nwal_log_hints setting:                on\nmax_connections setting:              100\nmax_worker_processes setting:         32\nmax_wal_senders setting:              10\nmax_prepared_xacts setting:           0\nmax_locks_per_xact setting:           64\ntrack_commit_timestamp setting:       off\nMaximum data alignment:               8\nDatabase block size:                  8192\nBlocks per segment of large relation: 131072\nWAL block size:                       8192\nBytes per WAL segment:                16777216\nMaximum length of identifiers:        64\nMaximum columns in an index:          32\nMaximum size of a TOAST chunk:        1996\nSize of a large-object chunk:         2048\nDate/time type storage:               64-bit integers\nFloat8 argument passing:              by value\nData page checksum version:           0\nMock authentication nonce:            b7f2f04197c763627732f064e0e1fca36c334973d9441ff8e49c207f6cd5a38f\n","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Starting up pg_rewind","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"]}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_rewind","msg":"pg_rewind: error: restore_command is not set in the target cluster","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:57Z","msg":"Failed to execute pg_rewind","logging_pod":"cluster-example-1","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"],"error":"exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*Instance).Rewind\n\tpkg/management/postgres/instance.go:783\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).verifyPgDataCoherenceForPrimary\n\tinternal/management/controller/instance_startup.go:235\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).initialize\n\tinternal/management/controller/instance_controller.go:327\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).Reconcile\n\tinternal/management/controller/instance_controller.go:141\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"pg_rewind failed, starting the server to complete the crash recovery","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"a8daf6ad-0a1e-46eb-891a-179e31abb133","uuid":"736bbc18-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","err":"error executing pg_rewind: exit status 1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Waiting for server to complete crash recovery","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Starting up instance","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["start","-w","-D","/var/lib/postgresql/data/pgdata","-o","-c port=5432 -c unix_socket_directories=/controller/run","-t 40000000"]}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"waiting for server to start....2023-03-23 15:21:57.805 GMT [56] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.806 GMT [56] LOG:  listening on IPv6 address \"::1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.806 GMT [56] LOG:  listening on IPv4 address \"127.0.0.1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.811 GMT [56] LOG:  listening on Unix socket \"/controller/run/.s.PGSQL.5432\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.813 GMT [56] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.813 GMT [56] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.813 GMT [56] CONTEXT:  line 6 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.813 GMT [56] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.813 GMT [56] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.813 GMT [56] CONTEXT:  line 7 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.813 GMT [56] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.813 GMT [56] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.813 GMT [56] CONTEXT:  line 8 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.817 GMT [59] LOG:  database system was shut down at 2023-03-23 15:15:11 GMT","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.817 GMT [59] LOG:  invalid primary checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.817 GMT [59] PANIC:  could not locate a valid checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.912 GMT [56] LOG:  startup process (PID 59) was terminated by signal 6: Aborted","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.912 GMT [56] LOG:  aborting startup due to startup process failure","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"2023-03-23 15:21:57.912 GMT [56] LOG:  database system is shut down","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Readiness probe failing","logging_pod":"cluster-example-1","err":"instance is not ready yet"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":" stopped waiting","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"pg_ctl: could not start server","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","logger":"pg_ctl","msg":"Examine the log output.","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Exited log pipe","fileName":"/controller/log/postgres.csv","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:57Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"a8daf6ad-0a1e-46eb-891a-179e31abb133","error":"while activating instance: error starting PostgreSQL instance: exit status 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"debug","ts":"2023-03-23T15:21:57Z","msg":"Reconciling Cluster","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"00938e91-8033-43a5-9818-1e5f926c74fe","uuid":"73927017-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:109","logging_pod":"cluster-example-1","cluster":{"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","namespace":"default","name":"cluster-example"}}
{"level":"debug","ts":"2023-03-23T15:21:57Z","msg":"Reconciling custom monitoring queries","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"00938e91-8033-43a5-9818-1e5f926c74fe","uuid":"73927017-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:727","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Cluster status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"00938e91-8033-43a5-9818-1e5f926c74fe","uuid":"73927017-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"This is an old primary instance, waiting for the switchover to finish","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"00938e91-8033-43a5-9818-1e5f926c74fe","uuid":"73927017-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Switchover completed","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"00938e91-8033-43a5-9818-1e5f926c74fe","uuid":"73927017-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","targetPrimary":"cluster-example-2","currentPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:57Z","msg":"Waiting for the new primary to be available","logging_pod":"cluster-example-1","primaryConnInfo":"host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres connect_timeout=5"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Extracting pg_controldata information","logging_pod":"cluster-example-1","reason":"before pg_rewind"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_controldata","msg":"pg_control version number:            1300\nCatalog version number:               202209061\nDatabase system identifier:           7213723966086483989\nDatabase cluster state:               shut down\npg_control last modified:             Thu 23 Mar 2023 03:15:11 PM UTC\nLatest checkpoint location:           0/8000028\nLatest checkpoint's REDO location:    0/8000028\nLatest checkpoint's REDO WAL file:    000000030000000000000008\nLatest checkpoint's TimeLineID:       3\nLatest checkpoint's PrevTimeLineID:   3\nLatest checkpoint's full_page_writes: on\nLatest checkpoint's NextXID:          0:741\nLatest checkpoint's NextOID:          24578\nLatest checkpoint's NextMultiXactId:  1\nLatest checkpoint's NextMultiOffset:  0\nLatest checkpoint's oldestXID:        716\nLatest checkpoint's oldestXID's DB:   1\nLatest checkpoint's oldestActiveXID:  0\nLatest checkpoint's oldestMultiXid:   1\nLatest checkpoint's oldestMulti's DB: 1\nLatest checkpoint's oldestCommitTsXid:0\nLatest checkpoint's newestCommitTsXid:0\nTime of latest checkpoint:            Thu 23 Mar 2023 03:15:10 PM UTC\nFake LSN counter for unlogged rels:   0/3E8\nMinimum recovery ending location:     0/0\nMin recovery ending loc's timeline:   0\nBackup start location:                0/0\nBackup end location:                  0/0\nEnd-of-backup record required:        no\nwal_level setting:                    logical\nwal_log_hints setting:                on\nmax_connections setting:              100\nmax_worker_processes setting:         32\nmax_wal_senders setting:              10\nmax_prepared_xacts setting:           0\nmax_locks_per_xact setting:           64\ntrack_commit_timestamp setting:       off\nMaximum data alignment:               8\nDatabase block size:                  8192\nBlocks per segment of large relation: 131072\nWAL block size:                       8192\nBytes per WAL segment:                16777216\nMaximum length of identifiers:        64\nMaximum columns in an index:          32\nMaximum size of a TOAST chunk:        1996\nSize of a large-object chunk:         2048\nDate/time type storage:               64-bit integers\nFloat8 argument passing:              by value\nData page checksum version:           0\nMock authentication nonce:            b7f2f04197c763627732f064e0e1fca36c334973d9441ff8e49c207f6cd5a38f\n","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Starting up pg_rewind","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"]}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_rewind","msg":"pg_rewind: error: restore_command is not set in the target cluster","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:58Z","msg":"Failed to execute pg_rewind","logging_pod":"cluster-example-1","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"],"error":"exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*Instance).Rewind\n\tpkg/management/postgres/instance.go:783\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).verifyPgDataCoherenceForPrimary\n\tinternal/management/controller/instance_startup.go:235\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).initialize\n\tinternal/management/controller/instance_controller.go:327\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).Reconcile\n\tinternal/management/controller/instance_controller.go:141\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"pg_rewind failed, starting the server to complete the crash recovery","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"00938e91-8033-43a5-9818-1e5f926c74fe","uuid":"73927017-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","err":"error executing pg_rewind: exit status 1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Waiting for server to complete crash recovery","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Starting up instance","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["start","-w","-D","/var/lib/postgresql/data/pgdata","-o","-c port=5432 -c unix_socket_directories=/controller/run","-t 40000000"]}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"waiting for server to start....2023-03-23 15:21:58.092 GMT [69] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.093 GMT [69] LOG:  listening on IPv6 address \"::1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.093 GMT [69] LOG:  listening on IPv4 address \"127.0.0.1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.098 GMT [69] LOG:  listening on Unix socket \"/controller/run/.s.PGSQL.5432\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.101 GMT [69] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.101 GMT [69] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.101 GMT [69] CONTEXT:  line 6 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.101 GMT [69] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.101 GMT [69] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.101 GMT [69] CONTEXT:  line 7 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.101 GMT [69] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.101 GMT [69] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.101 GMT [69] CONTEXT:  line 8 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.105 GMT [72] LOG:  database system was shut down at 2023-03-23 15:15:11 GMT","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.105 GMT [72] LOG:  invalid primary checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.105 GMT [72] PANIC:  could not locate a valid checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.198 GMT [69] LOG:  startup process (PID 72) was terminated by signal 6: Aborted","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.198 GMT [69] LOG:  aborting startup due to startup process failure","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.198 GMT [69] LOG:  database system is shut down","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"pg_ctl: could not start server","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"Examine the log output.","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":" stopped waiting","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Exited log pipe","fileName":"/controller/log/postgres.csv","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:58Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"00938e91-8033-43a5-9818-1e5f926c74fe","error":"while activating instance: error starting PostgreSQL instance: exit status 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"debug","ts":"2023-03-23T15:21:58Z","msg":"Reconciling Cluster","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c511afb7-99a0-414f-bf1d-28fcbf19ebe0","uuid":"73bb5b01-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:109","logging_pod":"cluster-example-1","cluster":{"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","namespace":"default","name":"cluster-example"}}
{"level":"debug","ts":"2023-03-23T15:21:58Z","msg":"Reconciling custom monitoring queries","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c511afb7-99a0-414f-bf1d-28fcbf19ebe0","uuid":"73bb5b01-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:727","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Cluster status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c511afb7-99a0-414f-bf1d-28fcbf19ebe0","uuid":"73bb5b01-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"This is an old primary instance, waiting for the switchover to finish","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c511afb7-99a0-414f-bf1d-28fcbf19ebe0","uuid":"73bb5b01-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Switchover completed","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c511afb7-99a0-414f-bf1d-28fcbf19ebe0","uuid":"73bb5b01-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","targetPrimary":"cluster-example-2","currentPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Waiting for the new primary to be available","logging_pod":"cluster-example-1","primaryConnInfo":"host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres connect_timeout=5"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Extracting pg_controldata information","logging_pod":"cluster-example-1","reason":"before pg_rewind"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_controldata","msg":"pg_control version number:            1300\nCatalog version number:               202209061\nDatabase system identifier:           7213723966086483989\nDatabase cluster state:               shut down\npg_control last modified:             Thu 23 Mar 2023 03:15:11 PM UTC\nLatest checkpoint location:           0/8000028\nLatest checkpoint's REDO location:    0/8000028\nLatest checkpoint's REDO WAL file:    000000030000000000000008\nLatest checkpoint's TimeLineID:       3\nLatest checkpoint's PrevTimeLineID:   3\nLatest checkpoint's full_page_writes: on\nLatest checkpoint's NextXID:          0:741\nLatest checkpoint's NextOID:          24578\nLatest checkpoint's NextMultiXactId:  1\nLatest checkpoint's NextMultiOffset:  0\nLatest checkpoint's oldestXID:        716\nLatest checkpoint's oldestXID's DB:   1\nLatest checkpoint's oldestActiveXID:  0\nLatest checkpoint's oldestMultiXid:   1\nLatest checkpoint's oldestMulti's DB: 1\nLatest checkpoint's oldestCommitTsXid:0\nLatest checkpoint's newestCommitTsXid:0\nTime of latest checkpoint:            Thu 23 Mar 2023 03:15:10 PM UTC\nFake LSN counter for unlogged rels:   0/3E8\nMinimum recovery ending location:     0/0\nMin recovery ending loc's timeline:   0\nBackup start location:                0/0\nBackup end location:                  0/0\nEnd-of-backup record required:        no\nwal_level setting:                    logical\nwal_log_hints setting:                on\nmax_connections setting:              100\nmax_worker_processes setting:         32\nmax_wal_senders setting:              10\nmax_prepared_xacts setting:           0\nmax_locks_per_xact setting:           64\ntrack_commit_timestamp setting:       off\nMaximum data alignment:               8\nDatabase block size:                  8192\nBlocks per segment of large relation: 131072\nWAL block size:                       8192\nBytes per WAL segment:                16777216\nMaximum length of identifiers:        64\nMaximum columns in an index:          32\nMaximum size of a TOAST chunk:        1996\nSize of a large-object chunk:         2048\nDate/time type storage:               64-bit integers\nFloat8 argument passing:              by value\nData page checksum version:           0\nMock authentication nonce:            b7f2f04197c763627732f064e0e1fca36c334973d9441ff8e49c207f6cd5a38f\n","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Starting up pg_rewind","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"]}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_rewind","msg":"pg_rewind: error: restore_command is not set in the target cluster","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:58Z","msg":"Failed to execute pg_rewind","logging_pod":"cluster-example-1","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"],"error":"exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*Instance).Rewind\n\tpkg/management/postgres/instance.go:783\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).verifyPgDataCoherenceForPrimary\n\tinternal/management/controller/instance_startup.go:235\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).initialize\n\tinternal/management/controller/instance_controller.go:327\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).Reconcile\n\tinternal/management/controller/instance_controller.go:141\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"pg_rewind failed, starting the server to complete the crash recovery","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c511afb7-99a0-414f-bf1d-28fcbf19ebe0","uuid":"73bb5b01-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","err":"error executing pg_rewind: exit status 1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Waiting for server to complete crash recovery","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Starting up instance","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["start","-w","-D","/var/lib/postgresql/data/pgdata","-o","-c port=5432 -c unix_socket_directories=/controller/run","-t 40000000"]}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"waiting for server to start....2023-03-23 15:21:58.327 GMT [83] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.327 GMT [83] LOG:  listening on IPv6 address \"::1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.327 GMT [83] LOG:  listening on IPv4 address \"127.0.0.1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.333 GMT [83] LOG:  listening on Unix socket \"/controller/run/.s.PGSQL.5432\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.336 GMT [83] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.336 GMT [83] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.336 GMT [83] CONTEXT:  line 6 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.336 GMT [83] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.336 GMT [83] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.336 GMT [83] CONTEXT:  line 7 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.336 GMT [83] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.336 GMT [83] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.336 GMT [83] CONTEXT:  line 8 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.340 GMT [86] LOG:  database system was shut down at 2023-03-23 15:15:11 GMT","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.340 GMT [86] LOG:  invalid primary checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.340 GMT [86] PANIC:  could not locate a valid checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.433 GMT [83] LOG:  startup process (PID 86) was terminated by signal 6: Aborted","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.434 GMT [83] LOG:  aborting startup due to startup process failure","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.434 GMT [83] LOG:  database system is shut down","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"pg_ctl: could not start server","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"Examine the log output.","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":" stopped waiting","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Exited log pipe","fileName":"/controller/log/postgres.csv","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:58Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"c511afb7-99a0-414f-bf1d-28fcbf19ebe0","error":"while activating instance: error starting PostgreSQL instance: exit status 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"debug","ts":"2023-03-23T15:21:58Z","msg":"Reconciling Cluster","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"bb80f22c-6a1b-41bd-a098-c51b275dcf8b","uuid":"73e20847-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:109","logging_pod":"cluster-example-1","cluster":{"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","namespace":"default","name":"cluster-example"}}
{"level":"debug","ts":"2023-03-23T15:21:58Z","msg":"Reconciling custom monitoring queries","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"bb80f22c-6a1b-41bd-a098-c51b275dcf8b","uuid":"73e20847-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:727","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Cluster status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"bb80f22c-6a1b-41bd-a098-c51b275dcf8b","uuid":"73e20847-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"This is an old primary instance, waiting for the switchover to finish","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"bb80f22c-6a1b-41bd-a098-c51b275dcf8b","uuid":"73e20847-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Switchover completed","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"bb80f22c-6a1b-41bd-a098-c51b275dcf8b","uuid":"73e20847-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","targetPrimary":"cluster-example-2","currentPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Waiting for the new primary to be available","logging_pod":"cluster-example-1","primaryConnInfo":"host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres connect_timeout=5"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Extracting pg_controldata information","logging_pod":"cluster-example-1","reason":"before pg_rewind"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_controldata","msg":"pg_control version number:            1300\nCatalog version number:               202209061\nDatabase system identifier:           7213723966086483989\nDatabase cluster state:               shut down\npg_control last modified:             Thu 23 Mar 2023 03:15:11 PM UTC\nLatest checkpoint location:           0/8000028\nLatest checkpoint's REDO location:    0/8000028\nLatest checkpoint's REDO WAL file:    000000030000000000000008\nLatest checkpoint's TimeLineID:       3\nLatest checkpoint's PrevTimeLineID:   3\nLatest checkpoint's full_page_writes: on\nLatest checkpoint's NextXID:          0:741\nLatest checkpoint's NextOID:          24578\nLatest checkpoint's NextMultiXactId:  1\nLatest checkpoint's NextMultiOffset:  0\nLatest checkpoint's oldestXID:        716\nLatest checkpoint's oldestXID's DB:   1\nLatest checkpoint's oldestActiveXID:  0\nLatest checkpoint's oldestMultiXid:   1\nLatest checkpoint's oldestMulti's DB: 1\nLatest checkpoint's oldestCommitTsXid:0\nLatest checkpoint's newestCommitTsXid:0\nTime of latest checkpoint:            Thu 23 Mar 2023 03:15:10 PM UTC\nFake LSN counter for unlogged rels:   0/3E8\nMinimum recovery ending location:     0/0\nMin recovery ending loc's timeline:   0\nBackup start location:                0/0\nBackup end location:                  0/0\nEnd-of-backup record required:        no\nwal_level setting:                    logical\nwal_log_hints setting:                on\nmax_connections setting:              100\nmax_worker_processes setting:         32\nmax_wal_senders setting:              10\nmax_prepared_xacts setting:           0\nmax_locks_per_xact setting:           64\ntrack_commit_timestamp setting:       off\nMaximum data alignment:               8\nDatabase block size:                  8192\nBlocks per segment of large relation: 131072\nWAL block size:                       8192\nBytes per WAL segment:                16777216\nMaximum length of identifiers:        64\nMaximum columns in an index:          32\nMaximum size of a TOAST chunk:        1996\nSize of a large-object chunk:         2048\nDate/time type storage:               64-bit integers\nFloat8 argument passing:              by value\nData page checksum version:           0\nMock authentication nonce:            b7f2f04197c763627732f064e0e1fca36c334973d9441ff8e49c207f6cd5a38f\n","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Starting up pg_rewind","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"]}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_rewind","msg":"pg_rewind: error: restore_command is not set in the target cluster","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:58Z","msg":"Failed to execute pg_rewind","logging_pod":"cluster-example-1","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"],"error":"exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*Instance).Rewind\n\tpkg/management/postgres/instance.go:783\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).verifyPgDataCoherenceForPrimary\n\tinternal/management/controller/instance_startup.go:235\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).initialize\n\tinternal/management/controller/instance_controller.go:327\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).Reconcile\n\tinternal/management/controller/instance_controller.go:141\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"pg_rewind failed, starting the server to complete the crash recovery","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"bb80f22c-6a1b-41bd-a098-c51b275dcf8b","uuid":"73e20847-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","err":"error executing pg_rewind: exit status 1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Waiting for server to complete crash recovery","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Starting up instance","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["start","-w","-D","/var/lib/postgresql/data/pgdata","-o","-c port=5432 -c unix_socket_directories=/controller/run","-t 40000000"]}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"waiting for server to start....2023-03-23 15:21:58.582 GMT [97] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.582 GMT [97] LOG:  listening on IPv6 address \"::1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.582 GMT [97] LOG:  listening on IPv4 address \"127.0.0.1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.587 GMT [97] LOG:  listening on Unix socket \"/controller/run/.s.PGSQL.5432\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.590 GMT [97] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.590 GMT [97] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.590 GMT [97] CONTEXT:  line 6 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.590 GMT [97] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.590 GMT [97] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.590 GMT [97] CONTEXT:  line 7 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.590 GMT [97] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.590 GMT [97] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.590 GMT [97] CONTEXT:  line 8 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.594 GMT [100] LOG:  database system was shut down at 2023-03-23 15:15:11 GMT","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.594 GMT [100] LOG:  invalid primary checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.594 GMT [100] PANIC:  could not locate a valid checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.688 GMT [97] LOG:  startup process (PID 100) was terminated by signal 6: Aborted","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.688 GMT [97] LOG:  aborting startup due to startup process failure","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.688 GMT [97] LOG:  database system is shut down","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":" stopped waiting","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"pg_ctl: could not start server","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"Examine the log output.","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Exited log pipe","fileName":"/controller/log/postgres.csv","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:58Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"bb80f22c-6a1b-41bd-a098-c51b275dcf8b","error":"while activating instance: error starting PostgreSQL instance: exit status 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"debug","ts":"2023-03-23T15:21:58Z","msg":"Reconciling Cluster","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"96f3b3d1-c793-4a71-98d4-b11609d3917c","uuid":"7408ed60-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:109","logging_pod":"cluster-example-1","cluster":{"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","namespace":"default","name":"cluster-example"}}
{"level":"debug","ts":"2023-03-23T15:21:58Z","msg":"Reconciling custom monitoring queries","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"96f3b3d1-c793-4a71-98d4-b11609d3917c","uuid":"7408ed60-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:727","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Cluster status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"96f3b3d1-c793-4a71-98d4-b11609d3917c","uuid":"7408ed60-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"This is an old primary instance, waiting for the switchover to finish","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"96f3b3d1-c793-4a71-98d4-b11609d3917c","uuid":"7408ed60-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Switchover completed","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"96f3b3d1-c793-4a71-98d4-b11609d3917c","uuid":"7408ed60-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","targetPrimary":"cluster-example-2","currentPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Waiting for the new primary to be available","logging_pod":"cluster-example-1","primaryConnInfo":"host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres connect_timeout=5"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Extracting pg_controldata information","logging_pod":"cluster-example-1","reason":"before pg_rewind"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_controldata","msg":"pg_control version number:            1300\nCatalog version number:               202209061\nDatabase system identifier:           7213723966086483989\nDatabase cluster state:               shut down\npg_control last modified:             Thu 23 Mar 2023 03:15:11 PM UTC\nLatest checkpoint location:           0/8000028\nLatest checkpoint's REDO location:    0/8000028\nLatest checkpoint's REDO WAL file:    000000030000000000000008\nLatest checkpoint's TimeLineID:       3\nLatest checkpoint's PrevTimeLineID:   3\nLatest checkpoint's full_page_writes: on\nLatest checkpoint's NextXID:          0:741\nLatest checkpoint's NextOID:          24578\nLatest checkpoint's NextMultiXactId:  1\nLatest checkpoint's NextMultiOffset:  0\nLatest checkpoint's oldestXID:        716\nLatest checkpoint's oldestXID's DB:   1\nLatest checkpoint's oldestActiveXID:  0\nLatest checkpoint's oldestMultiXid:   1\nLatest checkpoint's oldestMulti's DB: 1\nLatest checkpoint's oldestCommitTsXid:0\nLatest checkpoint's newestCommitTsXid:0\nTime of latest checkpoint:            Thu 23 Mar 2023 03:15:10 PM UTC\nFake LSN counter for unlogged rels:   0/3E8\nMinimum recovery ending location:     0/0\nMin recovery ending loc's timeline:   0\nBackup start location:                0/0\nBackup end location:                  0/0\nEnd-of-backup record required:        no\nwal_level setting:                    logical\nwal_log_hints setting:                on\nmax_connections setting:              100\nmax_worker_processes setting:         32\nmax_wal_senders setting:              10\nmax_prepared_xacts setting:           0\nmax_locks_per_xact setting:           64\ntrack_commit_timestamp setting:       off\nMaximum data alignment:               8\nDatabase block size:                  8192\nBlocks per segment of large relation: 131072\nWAL block size:                       8192\nBytes per WAL segment:                16777216\nMaximum length of identifiers:        64\nMaximum columns in an index:          32\nMaximum size of a TOAST chunk:        1996\nSize of a large-object chunk:         2048\nDate/time type storage:               64-bit integers\nFloat8 argument passing:              by value\nData page checksum version:           0\nMock authentication nonce:            b7f2f04197c763627732f064e0e1fca36c334973d9441ff8e49c207f6cd5a38f\n","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Starting up pg_rewind","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"]}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_rewind","msg":"pg_rewind: error: restore_command is not set in the target cluster","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:58Z","msg":"Failed to execute pg_rewind","logging_pod":"cluster-example-1","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"],"error":"exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*Instance).Rewind\n\tpkg/management/postgres/instance.go:783\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).verifyPgDataCoherenceForPrimary\n\tinternal/management/controller/instance_startup.go:235\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).initialize\n\tinternal/management/controller/instance_controller.go:327\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).Reconcile\n\tinternal/management/controller/instance_controller.go:141\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"pg_rewind failed, starting the server to complete the crash recovery","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"96f3b3d1-c793-4a71-98d4-b11609d3917c","uuid":"7408ed60-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","err":"error executing pg_rewind: exit status 1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Waiting for server to complete crash recovery","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Starting up instance","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["start","-w","-D","/var/lib/postgresql/data/pgdata","-o","-c port=5432 -c unix_socket_directories=/controller/run","-t 40000000"]}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"waiting for server to start....2023-03-23 15:21:58.835 GMT [111] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.836 GMT [111] LOG:  listening on IPv6 address \"::1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.836 GMT [111] LOG:  listening on IPv4 address \"127.0.0.1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.841 GMT [111] LOG:  listening on Unix socket \"/controller/run/.s.PGSQL.5432\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.844 GMT [111] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.844 GMT [111] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.844 GMT [111] CONTEXT:  line 6 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.844 GMT [111] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.844 GMT [111] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.844 GMT [111] CONTEXT:  line 7 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.844 GMT [111] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.844 GMT [111] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.844 GMT [111] CONTEXT:  line 8 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.848 GMT [114] LOG:  database system was shut down at 2023-03-23 15:15:11 GMT","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.848 GMT [114] LOG:  invalid primary checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.848 GMT [114] PANIC:  could not locate a valid checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","msg":"Readiness probe failing","logging_pod":"cluster-example-1","err":"instance is not ready yet"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.942 GMT [111] LOG:  startup process (PID 114) was terminated by signal 6: Aborted","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.942 GMT [111] LOG:  aborting startup due to startup process failure","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:58Z","logger":"pg_ctl","msg":"2023-03-23 15:21:58.943 GMT [111] LOG:  database system is shut down","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":" stopped waiting","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"pg_ctl: could not start server","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"Examine the log output.","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Exited log pipe","fileName":"/controller/log/postgres.csv","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:59Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"96f3b3d1-c793-4a71-98d4-b11609d3917c","error":"while activating instance: error starting PostgreSQL instance: exit status 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"debug","ts":"2023-03-23T15:21:59Z","msg":"Reconciling Cluster","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"ed11af4d-19b1-442c-af5e-1033c9fa7b0c","uuid":"742fa957-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:109","logging_pod":"cluster-example-1","cluster":{"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","namespace":"default","name":"cluster-example"}}
{"level":"debug","ts":"2023-03-23T15:21:59Z","msg":"Reconciling custom monitoring queries","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"ed11af4d-19b1-442c-af5e-1033c9fa7b0c","uuid":"742fa957-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:727","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Cluster status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"ed11af4d-19b1-442c-af5e-1033c9fa7b0c","uuid":"742fa957-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"This is an old primary instance, waiting for the switchover to finish","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"ed11af4d-19b1-442c-af5e-1033c9fa7b0c","uuid":"742fa957-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Switchover completed","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"ed11af4d-19b1-442c-af5e-1033c9fa7b0c","uuid":"742fa957-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","targetPrimary":"cluster-example-2","currentPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Waiting for the new primary to be available","logging_pod":"cluster-example-1","primaryConnInfo":"host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres connect_timeout=5"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Extracting pg_controldata information","logging_pod":"cluster-example-1","reason":"before pg_rewind"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_controldata","msg":"pg_control version number:            1300\nCatalog version number:               202209061\nDatabase system identifier:           7213723966086483989\nDatabase cluster state:               shut down\npg_control last modified:             Thu 23 Mar 2023 03:15:11 PM UTC\nLatest checkpoint location:           0/8000028\nLatest checkpoint's REDO location:    0/8000028\nLatest checkpoint's REDO WAL file:    000000030000000000000008\nLatest checkpoint's TimeLineID:       3\nLatest checkpoint's PrevTimeLineID:   3\nLatest checkpoint's full_page_writes: on\nLatest checkpoint's NextXID:          0:741\nLatest checkpoint's NextOID:          24578\nLatest checkpoint's NextMultiXactId:  1\nLatest checkpoint's NextMultiOffset:  0\nLatest checkpoint's oldestXID:        716\nLatest checkpoint's oldestXID's DB:   1\nLatest checkpoint's oldestActiveXID:  0\nLatest checkpoint's oldestMultiXid:   1\nLatest checkpoint's oldestMulti's DB: 1\nLatest checkpoint's oldestCommitTsXid:0\nLatest checkpoint's newestCommitTsXid:0\nTime of latest checkpoint:            Thu 23 Mar 2023 03:15:10 PM UTC\nFake LSN counter for unlogged rels:   0/3E8\nMinimum recovery ending location:     0/0\nMin recovery ending loc's timeline:   0\nBackup start location:                0/0\nBackup end location:                  0/0\nEnd-of-backup record required:        no\nwal_level setting:                    logical\nwal_log_hints setting:                on\nmax_connections setting:              100\nmax_worker_processes setting:         32\nmax_wal_senders setting:              10\nmax_prepared_xacts setting:           0\nmax_locks_per_xact setting:           64\ntrack_commit_timestamp setting:       off\nMaximum data alignment:               8\nDatabase block size:                  8192\nBlocks per segment of large relation: 131072\nWAL block size:                       8192\nBytes per WAL segment:                16777216\nMaximum length of identifiers:        64\nMaximum columns in an index:          32\nMaximum size of a TOAST chunk:        1996\nSize of a large-object chunk:         2048\nDate/time type storage:               64-bit integers\nFloat8 argument passing:              by value\nData page checksum version:           0\nMock authentication nonce:            b7f2f04197c763627732f064e0e1fca36c334973d9441ff8e49c207f6cd5a38f\n","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Starting up pg_rewind","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"]}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_rewind","msg":"pg_rewind: error: restore_command is not set in the target cluster","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:59Z","msg":"Failed to execute pg_rewind","logging_pod":"cluster-example-1","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"],"error":"exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*Instance).Rewind\n\tpkg/management/postgres/instance.go:783\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).verifyPgDataCoherenceForPrimary\n\tinternal/management/controller/instance_startup.go:235\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).initialize\n\tinternal/management/controller/instance_controller.go:327\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).Reconcile\n\tinternal/management/controller/instance_controller.go:141\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"pg_rewind failed, starting the server to complete the crash recovery","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"ed11af4d-19b1-442c-af5e-1033c9fa7b0c","uuid":"742fa957-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","err":"error executing pg_rewind: exit status 1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Waiting for server to complete crash recovery","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Starting up instance","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["start","-w","-D","/var/lib/postgresql/data/pgdata","-o","-c port=5432 -c unix_socket_directories=/controller/run","-t 40000000"]}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"waiting for server to start....2023-03-23 15:21:59.111 GMT [125] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.111 GMT [125] LOG:  listening on IPv6 address \"::1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.111 GMT [125] LOG:  listening on IPv4 address \"127.0.0.1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.124 GMT [125] LOG:  listening on Unix socket \"/controller/run/.s.PGSQL.5432\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.131 GMT [125] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.131 GMT [125] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.131 GMT [125] CONTEXT:  line 6 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.131 GMT [125] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.131 GMT [125] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.131 GMT [125] CONTEXT:  line 7 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.131 GMT [125] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.131 GMT [125] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.131 GMT [125] CONTEXT:  line 8 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.138 GMT [128] LOG:  database system was shut down at 2023-03-23 15:15:11 GMT","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.138 GMT [128] LOG:  invalid primary checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.138 GMT [128] PANIC:  could not locate a valid checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.229 GMT [125] LOG:  startup process (PID 128) was terminated by signal 6: Aborted","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.229 GMT [125] LOG:  aborting startup due to startup process failure","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.230 GMT [125] LOG:  database system is shut down","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":" stopped waiting","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"pg_ctl: could not start server","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"Examine the log output.","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Exited log pipe","fileName":"/controller/log/postgres.csv","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:59Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"ed11af4d-19b1-442c-af5e-1033c9fa7b0c","error":"while activating instance: error starting PostgreSQL instance: exit status 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"debug","ts":"2023-03-23T15:21:59Z","msg":"Reconciling Cluster","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"b44aabaa-c7d6-48a5-830c-746687d188c0","uuid":"74608e84-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:109","logging_pod":"cluster-example-1","cluster":{"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","namespace":"default","name":"cluster-example"}}
{"level":"debug","ts":"2023-03-23T15:21:59Z","msg":"Reconciling custom monitoring queries","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"b44aabaa-c7d6-48a5-830c-746687d188c0","uuid":"74608e84-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:727","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Cluster status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"b44aabaa-c7d6-48a5-830c-746687d188c0","uuid":"74608e84-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"This is an old primary instance, waiting for the switchover to finish","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"b44aabaa-c7d6-48a5-830c-746687d188c0","uuid":"74608e84-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Switchover completed","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"b44aabaa-c7d6-48a5-830c-746687d188c0","uuid":"74608e84-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","targetPrimary":"cluster-example-2","currentPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Waiting for the new primary to be available","logging_pod":"cluster-example-1","primaryConnInfo":"host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres connect_timeout=5"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Extracting pg_controldata information","logging_pod":"cluster-example-1","reason":"before pg_rewind"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_controldata","msg":"pg_control version number:            1300\nCatalog version number:               202209061\nDatabase system identifier:           7213723966086483989\nDatabase cluster state:               shut down\npg_control last modified:             Thu 23 Mar 2023 03:15:11 PM UTC\nLatest checkpoint location:           0/8000028\nLatest checkpoint's REDO location:    0/8000028\nLatest checkpoint's REDO WAL file:    000000030000000000000008\nLatest checkpoint's TimeLineID:       3\nLatest checkpoint's PrevTimeLineID:   3\nLatest checkpoint's full_page_writes: on\nLatest checkpoint's NextXID:          0:741\nLatest checkpoint's NextOID:          24578\nLatest checkpoint's NextMultiXactId:  1\nLatest checkpoint's NextMultiOffset:  0\nLatest checkpoint's oldestXID:        716\nLatest checkpoint's oldestXID's DB:   1\nLatest checkpoint's oldestActiveXID:  0\nLatest checkpoint's oldestMultiXid:   1\nLatest checkpoint's oldestMulti's DB: 1\nLatest checkpoint's oldestCommitTsXid:0\nLatest checkpoint's newestCommitTsXid:0\nTime of latest checkpoint:            Thu 23 Mar 2023 03:15:10 PM UTC\nFake LSN counter for unlogged rels:   0/3E8\nMinimum recovery ending location:     0/0\nMin recovery ending loc's timeline:   0\nBackup start location:                0/0\nBackup end location:                  0/0\nEnd-of-backup record required:        no\nwal_level setting:                    logical\nwal_log_hints setting:                on\nmax_connections setting:              100\nmax_worker_processes setting:         32\nmax_wal_senders setting:              10\nmax_prepared_xacts setting:           0\nmax_locks_per_xact setting:           64\ntrack_commit_timestamp setting:       off\nMaximum data alignment:               8\nDatabase block size:                  8192\nBlocks per segment of large relation: 131072\nWAL block size:                       8192\nBytes per WAL segment:                16777216\nMaximum length of identifiers:        64\nMaximum columns in an index:          32\nMaximum size of a TOAST chunk:        1996\nSize of a large-object chunk:         2048\nDate/time type storage:               64-bit integers\nFloat8 argument passing:              by value\nData page checksum version:           0\nMock authentication nonce:            b7f2f04197c763627732f064e0e1fca36c334973d9441ff8e49c207f6cd5a38f\n","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Starting up pg_rewind","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"]}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_rewind","msg":"pg_rewind: error: restore_command is not set in the target cluster","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:59Z","msg":"Failed to execute pg_rewind","logging_pod":"cluster-example-1","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"],"error":"exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*Instance).Rewind\n\tpkg/management/postgres/instance.go:783\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).verifyPgDataCoherenceForPrimary\n\tinternal/management/controller/instance_startup.go:235\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).initialize\n\tinternal/management/controller/instance_controller.go:327\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).Reconcile\n\tinternal/management/controller/instance_controller.go:141\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"pg_rewind failed, starting the server to complete the crash recovery","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"b44aabaa-c7d6-48a5-830c-746687d188c0","uuid":"74608e84-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","err":"error executing pg_rewind: exit status 1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Waiting for server to complete crash recovery","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Starting up instance","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["start","-w","-D","/var/lib/postgresql/data/pgdata","-o","-c port=5432 -c unix_socket_directories=/controller/run","-t 40000000"]}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"waiting for server to start....2023-03-23 15:21:59.412 GMT [139] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.412 GMT [139] LOG:  listening on IPv6 address \"::1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.412 GMT [139] LOG:  listening on IPv4 address \"127.0.0.1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.417 GMT [139] LOG:  listening on Unix socket \"/controller/run/.s.PGSQL.5432\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.422 GMT [139] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.422 GMT [139] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.422 GMT [139] CONTEXT:  line 6 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.422 GMT [139] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.422 GMT [139] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.422 GMT [139] CONTEXT:  line 7 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.422 GMT [139] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.422 GMT [139] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.422 GMT [139] CONTEXT:  line 8 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.425 GMT [142] LOG:  database system was shut down at 2023-03-23 15:15:11 GMT","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.426 GMT [142] LOG:  invalid primary checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.426 GMT [142] PANIC:  could not locate a valid checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.517 GMT [139] LOG:  startup process (PID 142) was terminated by signal 6: Aborted","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.517 GMT [139] LOG:  aborting startup due to startup process failure","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.518 GMT [139] LOG:  database system is shut down","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":" stopped waiting","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"pg_ctl: could not start server","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"Examine the log output.","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Exited log pipe","fileName":"/controller/log/postgres.csv","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:59Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"b44aabaa-c7d6-48a5-830c-746687d188c0","error":"while activating instance: error starting PostgreSQL instance: exit status 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"debug","ts":"2023-03-23T15:21:59Z","msg":"Reconciling Cluster","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"7735b71c-3645-4372-99a7-37c9daf1cb61","uuid":"749a96b6-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:109","logging_pod":"cluster-example-1","cluster":{"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","namespace":"default","name":"cluster-example"}}
{"level":"debug","ts":"2023-03-23T15:21:59Z","msg":"Reconciling custom monitoring queries","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"7735b71c-3645-4372-99a7-37c9daf1cb61","uuid":"749a96b6-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:727","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Cluster status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"7735b71c-3645-4372-99a7-37c9daf1cb61","uuid":"749a96b6-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"This is an old primary instance, waiting for the switchover to finish","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"7735b71c-3645-4372-99a7-37c9daf1cb61","uuid":"749a96b6-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Switchover completed","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"7735b71c-3645-4372-99a7-37c9daf1cb61","uuid":"749a96b6-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","targetPrimary":"cluster-example-2","currentPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Waiting for the new primary to be available","logging_pod":"cluster-example-1","primaryConnInfo":"host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres connect_timeout=5"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Extracting pg_controldata information","logging_pod":"cluster-example-1","reason":"before pg_rewind"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_controldata","msg":"pg_control version number:            1300\nCatalog version number:               202209061\nDatabase system identifier:           7213723966086483989\nDatabase cluster state:               shut down\npg_control last modified:             Thu 23 Mar 2023 03:15:11 PM UTC\nLatest checkpoint location:           0/8000028\nLatest checkpoint's REDO location:    0/8000028\nLatest checkpoint's REDO WAL file:    000000030000000000000008\nLatest checkpoint's TimeLineID:       3\nLatest checkpoint's PrevTimeLineID:   3\nLatest checkpoint's full_page_writes: on\nLatest checkpoint's NextXID:          0:741\nLatest checkpoint's NextOID:          24578\nLatest checkpoint's NextMultiXactId:  1\nLatest checkpoint's NextMultiOffset:  0\nLatest checkpoint's oldestXID:        716\nLatest checkpoint's oldestXID's DB:   1\nLatest checkpoint's oldestActiveXID:  0\nLatest checkpoint's oldestMultiXid:   1\nLatest checkpoint's oldestMulti's DB: 1\nLatest checkpoint's oldestCommitTsXid:0\nLatest checkpoint's newestCommitTsXid:0\nTime of latest checkpoint:            Thu 23 Mar 2023 03:15:10 PM UTC\nFake LSN counter for unlogged rels:   0/3E8\nMinimum recovery ending location:     0/0\nMin recovery ending loc's timeline:   0\nBackup start location:                0/0\nBackup end location:                  0/0\nEnd-of-backup record required:        no\nwal_level setting:                    logical\nwal_log_hints setting:                on\nmax_connections setting:              100\nmax_worker_processes setting:         32\nmax_wal_senders setting:              10\nmax_prepared_xacts setting:           0\nmax_locks_per_xact setting:           64\ntrack_commit_timestamp setting:       off\nMaximum data alignment:               8\nDatabase block size:                  8192\nBlocks per segment of large relation: 131072\nWAL block size:                       8192\nBytes per WAL segment:                16777216\nMaximum length of identifiers:        64\nMaximum columns in an index:          32\nMaximum size of a TOAST chunk:        1996\nSize of a large-object chunk:         2048\nDate/time type storage:               64-bit integers\nFloat8 argument passing:              by value\nData page checksum version:           0\nMock authentication nonce:            b7f2f04197c763627732f064e0e1fca36c334973d9441ff8e49c207f6cd5a38f\n","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Starting up pg_rewind","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"]}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_rewind","msg":"pg_rewind: error: restore_command is not set in the target cluster","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:59Z","msg":"Failed to execute pg_rewind","logging_pod":"cluster-example-1","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"],"error":"exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*Instance).Rewind\n\tpkg/management/postgres/instance.go:783\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).verifyPgDataCoherenceForPrimary\n\tinternal/management/controller/instance_startup.go:235\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).initialize\n\tinternal/management/controller/instance_controller.go:327\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).Reconcile\n\tinternal/management/controller/instance_controller.go:141\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"pg_rewind failed, starting the server to complete the crash recovery","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"7735b71c-3645-4372-99a7-37c9daf1cb61","uuid":"749a96b6-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","err":"error executing pg_rewind: exit status 1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Waiting for server to complete crash recovery","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Starting up instance","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["start","-w","-D","/var/lib/postgresql/data/pgdata","-o","-c port=5432 -c unix_socket_directories=/controller/run","-t 40000000"]}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"waiting for server to start....2023-03-23 15:21:59.804 GMT [153] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.804 GMT [153] LOG:  listening on IPv6 address \"::1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.804 GMT [153] LOG:  listening on IPv4 address \"127.0.0.1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.811 GMT [153] LOG:  listening on Unix socket \"/controller/run/.s.PGSQL.5432\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.817 GMT [153] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.817 GMT [153] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.817 GMT [153] CONTEXT:  line 6 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.817 GMT [153] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.817 GMT [153] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.817 GMT [153] CONTEXT:  line 7 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.817 GMT [153] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.817 GMT [153] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.817 GMT [153] CONTEXT:  line 8 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.821 GMT [157] LOG:  database system was shut down at 2023-03-23 15:15:11 GMT","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.821 GMT [157] LOG:  invalid primary checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.821 GMT [157] PANIC:  could not locate a valid checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.860 GMT [158] FATAL:  the database system is starting up","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: server error (FATAL: the database system is starting up (SQLSTATE 57P03))"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.915 GMT [153] LOG:  startup process (PID 157) was terminated by signal 6: Aborted","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.915 GMT [153] LOG:  aborting startup due to startup process failure","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"2023-03-23 15:21:59.915 GMT [153] LOG:  database system is shut down","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Readiness probe failing","logging_pod":"cluster-example-1","err":"instance is not ready yet"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":" stopped waiting","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"pg_ctl: could not start server","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","logger":"pg_ctl","msg":"Examine the log output.","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:21:59Z","msg":"Exited log pipe","fileName":"/controller/log/postgres.csv","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:21:59Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"7735b71c-3645-4372-99a7-37c9daf1cb61","error":"while activating instance: error starting PostgreSQL instance: exit status 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:22:00Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"debug","ts":"2023-03-23T15:22:00Z","msg":"Reconciling Cluster","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"fe3bc105-1f1b-4702-8a5d-88ccbb755738","uuid":"754ab4e0-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:109","logging_pod":"cluster-example-1","cluster":{"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","namespace":"default","name":"cluster-example"}}
{"level":"debug","ts":"2023-03-23T15:22:00Z","msg":"Reconciling custom monitoring queries","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"fe3bc105-1f1b-4702-8a5d-88ccbb755738","uuid":"754ab4e0-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:727","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","msg":"Cluster status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"fe3bc105-1f1b-4702-8a5d-88ccbb755738","uuid":"754ab4e0-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:22:00Z","msg":"This is an old primary instance, waiting for the switchover to finish","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"fe3bc105-1f1b-4702-8a5d-88ccbb755738","uuid":"754ab4e0-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:22:00Z","msg":"Switchover completed","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"fe3bc105-1f1b-4702-8a5d-88ccbb755738","uuid":"754ab4e0-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","targetPrimary":"cluster-example-2","currentPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:22:00Z","msg":"Waiting for the new primary to be available","logging_pod":"cluster-example-1","primaryConnInfo":"host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres connect_timeout=5"}
{"level":"info","ts":"2023-03-23T15:22:00Z","msg":"Extracting pg_controldata information","logging_pod":"cluster-example-1","reason":"before pg_rewind"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_controldata","msg":"pg_control version number:            1300\nCatalog version number:               202209061\nDatabase system identifier:           7213723966086483989\nDatabase cluster state:               shut down\npg_control last modified:             Thu 23 Mar 2023 03:15:11 PM UTC\nLatest checkpoint location:           0/8000028\nLatest checkpoint's REDO location:    0/8000028\nLatest checkpoint's REDO WAL file:    000000030000000000000008\nLatest checkpoint's TimeLineID:       3\nLatest checkpoint's PrevTimeLineID:   3\nLatest checkpoint's full_page_writes: on\nLatest checkpoint's NextXID:          0:741\nLatest checkpoint's NextOID:          24578\nLatest checkpoint's NextMultiXactId:  1\nLatest checkpoint's NextMultiOffset:  0\nLatest checkpoint's oldestXID:        716\nLatest checkpoint's oldestXID's DB:   1\nLatest checkpoint's oldestActiveXID:  0\nLatest checkpoint's oldestMultiXid:   1\nLatest checkpoint's oldestMulti's DB: 1\nLatest checkpoint's oldestCommitTsXid:0\nLatest checkpoint's newestCommitTsXid:0\nTime of latest checkpoint:            Thu 23 Mar 2023 03:15:10 PM UTC\nFake LSN counter for unlogged rels:   0/3E8\nMinimum recovery ending location:     0/0\nMin recovery ending loc's timeline:   0\nBackup start location:                0/0\nBackup end location:                  0/0\nEnd-of-backup record required:        no\nwal_level setting:                    logical\nwal_log_hints setting:                on\nmax_connections setting:              100\nmax_worker_processes setting:         32\nmax_wal_senders setting:              10\nmax_prepared_xacts setting:           0\nmax_locks_per_xact setting:           64\ntrack_commit_timestamp setting:       off\nMaximum data alignment:               8\nDatabase block size:                  8192\nBlocks per segment of large relation: 131072\nWAL block size:                       8192\nBytes per WAL segment:                16777216\nMaximum length of identifiers:        64\nMaximum columns in an index:          32\nMaximum size of a TOAST chunk:        1996\nSize of a large-object chunk:         2048\nDate/time type storage:               64-bit integers\nFloat8 argument passing:              by value\nData page checksum version:           0\nMock authentication nonce:            b7f2f04197c763627732f064e0e1fca36c334973d9441ff8e49c207f6cd5a38f\n","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","msg":"Starting up pg_rewind","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"]}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_rewind","msg":"pg_rewind: error: restore_command is not set in the target cluster","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:22:00Z","msg":"Failed to execute pg_rewind","logging_pod":"cluster-example-1","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"],"error":"exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*Instance).Rewind\n\tpkg/management/postgres/instance.go:783\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).verifyPgDataCoherenceForPrimary\n\tinternal/management/controller/instance_startup.go:235\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).initialize\n\tinternal/management/controller/instance_controller.go:327\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).Reconcile\n\tinternal/management/controller/instance_controller.go:141\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:22:00Z","msg":"pg_rewind failed, starting the server to complete the crash recovery","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"fe3bc105-1f1b-4702-8a5d-88ccbb755738","uuid":"754ab4e0-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","err":"error executing pg_rewind: exit status 1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","msg":"Waiting for server to complete crash recovery","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","msg":"Starting up instance","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["start","-w","-D","/var/lib/postgresql/data/pgdata","-o","-c port=5432 -c unix_socket_directories=/controller/run","-t 40000000"]}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"waiting for server to start....2023-03-23 15:22:00.954 GMT [168] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"2023-03-23 15:22:00.954 GMT [168] LOG:  listening on IPv6 address \"::1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"2023-03-23 15:22:00.954 GMT [168] LOG:  listening on IPv4 address \"127.0.0.1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"2023-03-23 15:22:00.962 GMT [168] LOG:  listening on Unix socket \"/controller/run/.s.PGSQL.5432\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"2023-03-23 15:22:00.965 GMT [168] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"2023-03-23 15:22:00.965 GMT [168] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"2023-03-23 15:22:00.965 GMT [168] CONTEXT:  line 6 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"2023-03-23 15:22:00.965 GMT [168] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"2023-03-23 15:22:00.965 GMT [168] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"2023-03-23 15:22:00.965 GMT [168] CONTEXT:  line 7 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"2023-03-23 15:22:00.965 GMT [168] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"2023-03-23 15:22:00.965 GMT [168] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"2023-03-23 15:22:00.965 GMT [168] CONTEXT:  line 8 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"2023-03-23 15:22:00.970 GMT [171] LOG:  database system was shut down at 2023-03-23 15:15:11 GMT","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"2023-03-23 15:22:00.970 GMT [171] LOG:  invalid primary checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:00Z","logger":"pg_ctl","msg":"2023-03-23 15:22:00.970 GMT [171] PANIC:  could not locate a valid checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:01Z","logger":"pg_ctl","msg":"2023-03-23 15:22:01.064 GMT [168] LOG:  startup process (PID 171) was terminated by signal 6: Aborted","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:01Z","logger":"pg_ctl","msg":"2023-03-23 15:22:01.064 GMT [168] LOG:  aborting startup due to startup process failure","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:01Z","logger":"pg_ctl","msg":"2023-03-23 15:22:01.065 GMT [168] LOG:  database system is shut down","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:01Z","logger":"pg_ctl","msg":" stopped waiting","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:01Z","logger":"pg_ctl","msg":"pg_ctl: could not start server","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:01Z","logger":"pg_ctl","msg":"Examine the log output.","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:01Z","msg":"Exited log pipe","fileName":"/controller/log/postgres.csv","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:22:01Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"fe3bc105-1f1b-4702-8a5d-88ccbb755738","error":"while activating instance: error starting PostgreSQL instance: exit status 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:22:01Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:01Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:01Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:01Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:01Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:02Z","msg":"Readiness probe failing","logging_pod":"cluster-example-1","err":"instance is not ready yet"}
{"level":"info","ts":"2023-03-23T15:22:03Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:03Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:03Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:03Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:03Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:04Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:05Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:05Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:05Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:05Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"debug","ts":"2023-03-23T15:22:06Z","msg":"Reconciling Cluster","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"581eab1d-6a47-4a58-9212-eac8456aef48","uuid":"787f7ec4-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:109","logging_pod":"cluster-example-1","cluster":{"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","namespace":"default","name":"cluster-example"}}
{"level":"debug","ts":"2023-03-23T15:22:06Z","msg":"Reconciling custom monitoring queries","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"581eab1d-6a47-4a58-9212-eac8456aef48","uuid":"787f7ec4-c98e-11ed-a8e7-62f6ad84cc39","caller":"internal/management/controller/instance_controller.go:727","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","msg":"Cluster status","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"581eab1d-6a47-4a58-9212-eac8456aef48","uuid":"787f7ec4-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:22:06Z","msg":"This is an old primary instance, waiting for the switchover to finish","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"581eab1d-6a47-4a58-9212-eac8456aef48","uuid":"787f7ec4-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","currentPrimary":"cluster-example-2","targetPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:22:06Z","msg":"Switchover completed","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"581eab1d-6a47-4a58-9212-eac8456aef48","uuid":"787f7ec4-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","targetPrimary":"cluster-example-2","currentPrimary":"cluster-example-2"}
{"level":"info","ts":"2023-03-23T15:22:06Z","msg":"Waiting for the new primary to be available","logging_pod":"cluster-example-1","primaryConnInfo":"host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres connect_timeout=5"}
{"level":"info","ts":"2023-03-23T15:22:06Z","msg":"Extracting pg_controldata information","logging_pod":"cluster-example-1","reason":"before pg_rewind"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_controldata","msg":"pg_control version number:            1300\nCatalog version number:               202209061\nDatabase system identifier:           7213723966086483989\nDatabase cluster state:               shut down\npg_control last modified:             Thu 23 Mar 2023 03:15:11 PM UTC\nLatest checkpoint location:           0/8000028\nLatest checkpoint's REDO location:    0/8000028\nLatest checkpoint's REDO WAL file:    000000030000000000000008\nLatest checkpoint's TimeLineID:       3\nLatest checkpoint's PrevTimeLineID:   3\nLatest checkpoint's full_page_writes: on\nLatest checkpoint's NextXID:          0:741\nLatest checkpoint's NextOID:          24578\nLatest checkpoint's NextMultiXactId:  1\nLatest checkpoint's NextMultiOffset:  0\nLatest checkpoint's oldestXID:        716\nLatest checkpoint's oldestXID's DB:   1\nLatest checkpoint's oldestActiveXID:  0\nLatest checkpoint's oldestMultiXid:   1\nLatest checkpoint's oldestMulti's DB: 1\nLatest checkpoint's oldestCommitTsXid:0\nLatest checkpoint's newestCommitTsXid:0\nTime of latest checkpoint:            Thu 23 Mar 2023 03:15:10 PM UTC\nFake LSN counter for unlogged rels:   0/3E8\nMinimum recovery ending location:     0/0\nMin recovery ending loc's timeline:   0\nBackup start location:                0/0\nBackup end location:                  0/0\nEnd-of-backup record required:        no\nwal_level setting:                    logical\nwal_log_hints setting:                on\nmax_connections setting:              100\nmax_worker_processes setting:         32\nmax_wal_senders setting:              10\nmax_prepared_xacts setting:           0\nmax_locks_per_xact setting:           64\ntrack_commit_timestamp setting:       off\nMaximum data alignment:               8\nDatabase block size:                  8192\nBlocks per segment of large relation: 131072\nWAL block size:                       8192\nBytes per WAL segment:                16777216\nMaximum length of identifiers:        64\nMaximum columns in an index:          32\nMaximum size of a TOAST chunk:        1996\nSize of a large-object chunk:         2048\nDate/time type storage:               64-bit integers\nFloat8 argument passing:              by value\nData page checksum version:           0\nMock authentication nonce:            b7f2f04197c763627732f064e0e1fca36c334973d9441ff8e49c207f6cd5a38f\n","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","msg":"Starting up pg_rewind","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"]}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_rewind","msg":"pg_rewind: error: restore_command is not set in the target cluster","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:22:06Z","msg":"Failed to execute pg_rewind","logging_pod":"cluster-example-1","options":["-P","--source-server","host=cluster-example-rw user=streaming_replica port=5432 sslkey=/controller/certificates/streaming_replica.key sslcert=/controller/certificates/streaming_replica.crt sslrootcert=/controller/certificates/server-ca.crt application_name=cluster-example-1 sslmode=verify-ca dbname=postgres","--target-pgdata","/var/lib/postgresql/data/pgdata","--restore-target-wal"],"error":"exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:166\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*Instance).Rewind\n\tpkg/management/postgres/instance.go:783\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).verifyPgDataCoherenceForPrimary\n\tinternal/management/controller/instance_startup.go:235\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).initialize\n\tinternal/management/controller/instance_controller.go:327\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller.(*InstanceReconciler).Reconcile\n\tinternal/management/controller/instance_controller.go:141\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:22:06Z","msg":"pg_rewind failed, starting the server to complete the crash recovery","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"581eab1d-6a47-4a58-9212-eac8456aef48","uuid":"787f7ec4-c98e-11ed-a8e7-62f6ad84cc39","logging_pod":"cluster-example-1","err":"error executing pg_rewind: exit status 1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","msg":"Waiting for server to complete crash recovery","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","msg":"Starting up instance","logging_pod":"cluster-example-1","pgdata":"/var/lib/postgresql/data/pgdata","options":["start","-w","-D","/var/lib/postgresql/data/pgdata","-o","-c port=5432 -c unix_socket_directories=/controller/run","-t 40000000"]}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"waiting for server to start....2023-03-23 15:22:06.322 GMT [182] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.323 GMT [182] LOG:  listening on IPv6 address \"::1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.323 GMT [182] LOG:  listening on IPv4 address \"127.0.0.1\", port 5432","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.328 GMT [182] LOG:  listening on Unix socket \"/controller/run/.s.PGSQL.5432\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.331 GMT [182] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.331 GMT [182] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.331 GMT [182] CONTEXT:  line 6 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.331 GMT [182] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.331 GMT [182] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.331 GMT [182] CONTEXT:  line 7 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.331 GMT [182] LOG:  hostssl record cannot match because SSL is disabled","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.331 GMT [182] HINT:  Set ssl = on in postgresql.conf.","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.331 GMT [182] CONTEXT:  line 8 of configuration file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\"","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.335 GMT [187] LOG:  database system was shut down at 2023-03-23 15:15:11 GMT","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.335 GMT [187] LOG:  invalid primary checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.335 GMT [187] PANIC:  could not locate a valid checkpoint record","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.428 GMT [182] LOG:  startup process (PID 187) was terminated by signal 6: Aborted","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.428 GMT [182] LOG:  aborting startup due to startup process failure","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"2023-03-23 15:22:06.428 GMT [182] LOG:  database system is shut down","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":" stopped waiting","pipe":"stdout","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"pg_ctl: could not start server","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","logger":"pg_ctl","msg":"Examine the log output.","pipe":"stderr","logging_pod":"cluster-example-1"}
{"level":"info","ts":"2023-03-23T15:22:06Z","msg":"Exited log pipe","fileName":"/controller/log/postgres.csv","logging_pod":"cluster-example-1"}
{"level":"error","ts":"2023-03-23T15:22:06Z","msg":"Reconciler error","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"cluster-example","namespace":"default"},"namespace":"default","name":"cluster-example","reconcileID":"581eab1d-6a47-4a58-9212-eac8456aef48","error":"while activating instance: error starting PostgreSQL instance: exit status 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
{"level":"info","ts":"2023-03-23T15:22:06Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:06Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:06Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:06Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:07Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:08Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:08Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:08Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:08Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
{"level":"info","ts":"2023-03-23T15:22:08Z","msg":"Instance status probe failing","logging_pod":"cluster-example-1","err":"failed to connect to `host=/controller/run user=postgres database=postgres`: dial error (dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory)"}
